### ISSUE TITLE
第7回輪読会の感想とか書いてー

### ISSUE THREAD

**Issue by ryutah** [dokurin/dokushokai#10]
せっかくなので、各自の感想と反省とかをまとめてもらいたいなーと思い。

あとで適当にまとめるので、暇な時にコメントしといてくださいー

---

# 原感想・反省
## 感想
* まあやってよかったと思う
* ドメインモデルの粒度はやっぱ難しいなーと思った
  - ドメインの属性全部書くの？
  - FactoryとかRepositoryってほんとにドメインモデルに必要。。。？
* 業務への理解が足りないとやっぱ辛いわ
* DDD本読み終わったら、今回作成したドメインモデルとかを振り返ってみたいなーと思った

## 反省
* システムの要求と登場人物の整理とかは事前にもっとしっかり詰めといたほうが良かった感
* 数時間でやるにしてはスコープが大きすぎたと思う
  - プログラムのプロトタイプまで書くなら貨物予約だけをシステム化の範囲にする
  - ドメインモデルの作成までを作業スコープにする
* 簡単なタイムテーブルを用意しといても良かったかも
  - 何時までにドメインモデル完成させるとか、時間制限もたせといたほうがスムーズに進行できた気がする

**Comment by yoshioH** [comment]
# 感想
最終的に納得のいくモデル図を作ることができた。
思った以上に仕事っぽい進み方になったけれども、仕事ほどストレスを感じずに進められたのはみんなの気遣いのお陰だと思う。
ダラダラしゃべることもあったけれども、テーマが決まっていたからか、普通の飲み会よりも過ごしやすかった。

レイヤーとドメインの話は難しいね。。。

# 反省
- 当日の進め方にもっと気を使うべきだった
  - シーケンス図を序盤で描いてしまったため、目的のない業務フローが先行してしまった。そのため、システムよりの細かい話に引きづられた
  - 途中でコーディングを捨てたのはよかった
  - 登場人物の定義や本来の業務を明確にしないまま進めてしまった
    - 要所で立ち戻ることができたし、悔やむことはないと思う
    - とはいえ、ロスを少なくするためにも、立ち戻りポイントに気づくための精度を上げたい
- @ryutah にかなり負担が行ってしまった
  - こんな感じで役割分担をもう少し決めるだけでもちょっと変わるかな？
    - ドメインエキスパート役（プロダクトオーナー）
    - 進行役（スクラムマスター）
    - 書記役（開発チーム）
- ユビキタス言語以外の言葉の定義が疎かになりがちだった
  - UML（というよりクラス図）への理解が意外とゆるふわ
- 時間の区切り方
  - キリのいいところまでという名目でダラダラ続けてしまったところがある
  - 解禁したら飲みっぱなしになったので、ドリンクタイムとチェイサータイムを入れてみませんか？

**Comment by ryutah** [comment]
Wikiに書いたんでCloseしちゃう
