### ISSUE TITLE
[飲み会やるやる] 日程決め

### ISSUE THREAD

**Issue by ryutah** [dokurin/dokushokai#26]
## 候補日
- 4/4 (土)
- 4/5 (日)
- 4/11 (土)
- 4/12 (日)

**Comment by ryutah** [comment]
個人的には日曜より土曜がいいなって気持ち。

**Comment by yoshioH** [comment]
当面、フラペチーノ社畜 @itor319 が来れないのほぼ確定だし、金曜日でもいい気がする。

**Comment by yoshioH** [comment]
温泉行くなら土曜日、飲みだけなら金曜日かな。
