### ISSUE TITLE
[飲み会やるやる] 場所決め

### ISSUE THREAD

**Issue by ryutah** [dokurin/dokushokai#27]
## 候補
- 熱海
- 小田原
- 箱根

**Comment by yoshioH** [comment]
- 熱海
  * 辺境のイメージ
  * 宿泊温泉街だから食事できるところが少ないかも？
- 小田原
  * けっこうお店がある(3つの候補地の中で一番だと思う)
- 箱根
  * [天成園](https://www.tenseien.co.jp/) いこうぜー
    - 日帰り温泉あり
    - 日帰りでも個室を借りられるぽい

てことで、個人的には↓の序列。
- **松** 箱根で日帰り温泉
- **竹** 小田原
- **梅** 熱海

**Comment by ryutah** [comment]
(オンライン飲み会とかでいいんじゃないかという気持ちになってきた)
