### ISSUE TITLE
Ⅰ 始計篇

### ISSUE THREAD

**Issue by itor319** [dokurin/dokushokai#64]

**Comment by itor319** [comment]
経済学の視点では、戦争は「最終経済」と呼ばれ、「生産がなく消耗だけである」とされてるらしい。

**Comment by itor319** [comment]
５つの基本問題
------
**道**
国民と君主は一心同体になら国民は危険を恐れないし君主と生死をともにする。
　→　大義名分のことらしい。こいつが無ければ兵隊が頑張る理由がないよねってことだと思う。

**天**
昼夜、晴雨、寒暑、季節などの時間的条件を指す。
　→　タイミングって大事よね。

**地**
行程の感覚、地勢の険阻、地域の広さ、地形の有利不利などの地理的条件を指す。
　→　地の利。

**将**
智謀、信義、仁慈、勇気、威厳など将帥の器量に関わる問題。
　→　組織のリーダーの条件らしい。要は人として尊敬されるような人が好ましいって感じ？

**法**
軍の編成、職責分担、軍需物資の管理など軍制に関わる問題。
　→　組織のルール決めのことっぽい？給与体系大事だし。

上記をちゃんと理解してないと勝てへんで。

**Comment by ryutah** [comment]
へー

**Comment by yoshioH** [comment]
やっぱり孫子はいいね。
高校生の時に読んだときは地の利点ってのがピンとこなかったけど、今ならちょっと分かるわ。とはいえ、Javaの人はJavaの仕事をするのが適してるってだけの話なんだけど。

**Comment by itor319** [comment]
**七つの基本条件**
-----
***一, 君主は、どちらが立派な政治を行っているか***

***二, 将帥は、どちらが有能であるか***

***三, 天の時と地の利は、どちらに有利であるか***

***四, 法令は、どちらが徹底しているか***

***五, 軍隊は、どちらが精強であるか***

***六, 兵卒は、どちらが訓練されているか***

***七, 賞罰は、どちらが公正に行われているか***

**Comment by itor319** [comment]
自国の事だけじゃなく、敵国の事も知らなきゃ勝てないぞ、ということなんだろうけど。
軍事力の事だけじゃなく、政治の面でも知らなきゃいけないとのこと。
いまいちピンと来てないのは猫が政治を知らなさすぎるからかもしれない…。

※政治を政治として考えるとむずいので、「生産力をどのように上げているか」とかって置き換えると納得行くかも

**Comment by itor319** [comment]
**仕える条件**  

王 が、 もし わたし の はかり ごと を 用い、 軍師 として 登用 する なら、 必ず 勝利 を 収める こと が できる。 それなら、 わたし は 貴国 に とどまろ う。 逆 に わたし の はかり ごと を 用い なけれ ば、 かりに 軍師 として 戦い に のぞん だ として も、 必ず 敗れる。 それなら、 わたし は 貴国 に とどまる 意志 は ない。

-----

人より策に投資しろってことかね？

**Comment by itor319** [comment]
**基本と応用**

「勢」を把握して、基本条件を補強することである。
勢＝状況に応じて臨機応変に対処すること。

-----

基本に忠実なのは当たり前で、勝つためには基本と応用の両面を上手にやる必要があるとのこと。
三国志に登場した蜀に属する馬謖が体現してくれたやろ、と。
基本通りに高いとこ陣取ったら囲まれて補給線をやられたから降りたらボコられた。可愛そう（KONAMI）

**Comment by ryutah** [comment]
はえー

**Comment by itor319** [comment]
**兵は詭道なり**

戦争とは、騙し合いである。
意外とボクシングもそうらしく、輪島功一の戦法（戦術？）も孫子の兵法の要諦にかなってたとか。

------

騙し合いするためには、それこそ相手の状況とかそういうの知ってなきゃできないよなーと思いましたまる

**Comment by itor319** [comment]
**勝利の見通し**

勝利の見通しが立つというのは「勝つための条件が揃っている」からで、逆に見通しが立たないのは「勝つための条件が揃っていない」からである。
条件が整っていれば勝てるし、整って無ければ負ける。
条件がまったく無ければ、まるで問題にならない。
この観点に立つなら、勝敗は戦わずして明らかになる。

-----

「勝算が無ければ戦わない」は、孫氏の基本認識。
5つの基本問題も7つの基本条件も、勝算の有る無しを明らかにするため。
それらは可能だし、必要不可欠な前提であると孫武は考えていたらしい。

ただ、「条件がまったく無ければ問題にならない」の意味合いが、「楽勝ゲームになるわー」って意味なのか、「条件がないんだから戦うな」って意味なのか、はたまた別の意味合いなのかがよくわからん。

**Comment by itor319** [comment]
まとめると、5つの基本問題と7つの基本条件っていう考えることリストがある。
これを正しく理解して、考えましょうってことだと思う（小並感）

　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　終
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　制作・著作
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　━━━━━
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　始計篇

**Comment by yoshioH** [comment]
> 条件がまったく無ければ問題にならない

は条件がないんだから戦うなって意味だろうね。
例えば、**六, 兵卒は、どちらが訓練されているか** の条件がないってどんな状態なのかを考えてみよう。
多分、まったく訓練を受けていない素人の寄せ集めって意味になる。過激な例えをすると、NEETの寄せ集めとか。もはや軍隊というより集団。どんな超絶無敵の異世界転生俺TUEEEEE主人公が指揮しても絶対に勝てないと思う。
逆にいうと敵国がそういう状態なら、他の6つの基本条件が全部劣っていても戦争に持ち込めば絶対に勝てるはず。そういう意味で言えば楽勝って意味にもなる。
